In [25]:
# Task 1.1 

nums = [3,5,7,8,12]
cubes = []
for i in nums:
    cubes.append(i**3)
print(cubes)


[27, 125, 343, 512, 1728]


In [26]:
# Task 1.2

dict = {}
dict['parrot'] = 2
dict['goat'] = 4
dict['spider'] = 8
dict['crab'] = 10
print(dict)
TOTAL_LEGS = 0;
for animal,legs in dict.items():
    print(f"{animal}, {legs}")
    TOTAL_LEGS = TOTAL_LEGS + legs;

print(TOTAL_LEGS)


{'parrot': 2, 'goat': 4, 'spider': 8, 'crab': 10}
parrot, 2
goat, 4
spider, 8
crab, 10
24


In [27]:
# Task 1.3

A = (3,9,4,[5,6])
A[3][0] = 8 
print(A)


(3, 9, 4, [8, 6])


In [28]:
# Task 1.4
del A


In [29]:
print(A)


NameError: name 'A' is not defined

In [30]:
# Task 1.5
B = ('a','p','p','l','e')
count = B.count('p')
print(count)


2


In [31]:
# Task 1.6
B = ('a','p','p','l','e')
index = B.index('l')
print(index)


3


In [32]:
# Task 2.1
import numpy as np

A = np.array([[1,2,3,4],
      [5,6,7,8],
      [9,10,11,12]])
print(A)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
# Task 2.2
b = A[0:2,0:2]
print(b)


[[1 2]
 [5 6]]


In [34]:
# Task 2.3 
c = np.empty_like(A)
print(c)

# The exact content of C will be random, as np.empty() does not initialize the array entries. 

[[4128860 6029375 7274573 7209077]
 [5242996 6881391 7602286 6357069]
 [6357102 6619239     114 3407973]]


In [35]:
# Task 2.4
z = np.array([1, 0, 1])
for i in range(A.shape[1]):
    c[:, i] = A[:, i] + z
print(c)


[[ 2  3  4  5]
 [ 5  6  7  8]
 [10 11 12 13]]


In [36]:
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
v = np.array([9,10])
# Task 2.5
Addition = X + Y
print(Addition)


[[ 6  8]
 [10 12]]


In [20]:
# Task 2.6
Multiplication = X*Y
print(Multiplication)


[[ 5 12]
 [21 32]]


In [37]:
# Task 2.7
Square_root = np.sqrt(Y)
print(Square_root)


[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [38]:
# Task 2.8
Dot_product = np.dot(X, v)
print(Dot_product)


[29 67]


In [39]:
# Task 2.9
Sum = np.sum(X, axis=0)
print(Sum)


[4 6]


In [40]:
# Task 3.1
def compute( distance, time):
    if time == 0:
        return "Time cannot be zero"
    velocity = distance/time
    return velocity
velocity = compute( 50, 0)
print(velocity)


Time cannot be zero


In [10]:
velocity = compute( 50, 10)
print(velocity)


5.0


In [41]:
# Task 3.2
even_num = [2,4,6,8,10,12]
def mult(even_num):
    product = 1
    for num in even_num:
        product *= num
    return product

result = mult(even_num)
print(result)


46080


In [42]:
# Task 4
import pandas as pd
data =  {
    'C1': [1, 2, 3, 5, 5],
    'C2': [6, 7, 5, 4, 8],
    'C3': [7, 9, 8, 6, 5],
    'C4': [7, 5, 2, 8, 8]
}
df = pd.DataFrame(data)
print(df)


   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [43]:
# Task 4.1
print(df.head(2))


   C1  C2  C3  C4
0   1   6   7   7
1   2   7   9   5


In [44]:
# Task 4.2
print(df['C2'])


0    6
1    7
2    5
3    4
4    8
Name: C2, dtype: int64


In [49]:
# Task 4.3
df.rename(columns = { 'C3':'B3'})
print(df)


   C1  C2  B3  C4
0   1   6   7   7
1   2   7   9   5
2   3   5   8   2
3   5   4   6   8
4   5   8   5   8


In [54]:
# Task 4.4
df['Sum'] = 0
print(df)


   C1  C2  B3  C4  Sum
0   1   6   7   7    0
1   2   7   9   5    0
2   3   5   8   2    0
3   5   4   6   8    0
4   5   8   5   8    0


In [55]:
# Task 4.5
df['Sum'] = df.sum(axis = 1)
print(df)


   C1  C2  B3  C4  Sum
0   1   6   7   7   21
1   2   7   9   5   23
2   3   5   8   2   18
3   5   4   6   8   23
4   5   8   5   8   26


In [62]:
# Task 4.6
df_csv = pd.read_csv('hello_sample.csv')


In [63]:
# Task 4.7
print(df_csv)


    Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66


In [64]:
# Task 4.8
print(df_csv.tail(2))


   Gender F_Color     B_Month  Weight
21   Male  Yellow       April      74
22   Male     Red  September       66


In [65]:
# Task 4.9
df_csv.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Gender   23 non-null     object
 1   F_Color  23 non-null     object
 2   B_Month  23 non-null     object
 3   Weight   23 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 868.0+ bytes


In [66]:
# Task 4.10
print(df_csv.shape)


(23, 4)


In [67]:
# Task 4.11
df_csv_sorted = df_csv.sort_values(by='Weight')
print(df_csv_sorted)


    Gender  F_Color     B_Month  Weight
2     Male    Black     October      53
16    Male    Black      August      54
9     Male     Blue         May      58
7   Female      Red   September      59
18    Male  Mustard   December       60
10  Female      Red    October       60
6     Male   Orange      August      60
8     Male     Blue        July      60
3   Female     Blue    February      63
11    Male    Black   September      65
22    Male      Red  September       66
20    Male    Black   February       67
13    Male    Black       April      72
1     Male      Red       March      72
21    Male   Yellow       April      74
19  Female    Black    October       76
0     Male    Black       March      77
4     Male    black    October       80
17    Male    Black     January      82
12    Male    Green    December      85
14    Male    Green    January       90
15    Male   Yellow   November       90
5   Female    Black    december      97


In [68]:
# Task 4.12
df_csv.isnull()


Gender  F_Color  B_Month  Weight
0    False    False    False   False
1    False    False    False   False
2    False    False    False   False
3    False    False    False   False
4    False    False    False   False
5    False    False    False   False
6    False    False    False   False
7    False    False    False   False
8    False    False    False   False
9    False    False    False   False
10   False    False    False   False
11   False    False    False   False
12   False    False    False   False
13   False    False    False   False
14   False    False    False   False
15   False    False    False   False
16   False    False    False   False
17   False    False    False   False
18   False    False    False   False
19   False    False    False   False
20   False    False    False   False
21   False    False    False   False
22   False    False    False   False

In [69]:
df_csv.dropna()


Gender  F_Color     B_Month  Weight
0     Male    Black       March      77
1     Male      Red       March      72
2     Male    Black     October      53
3   Female     Blue    February      63
4     Male    black    October       80
5   Female    Black    december      97
6     Male   Orange      August      60
7   Female      Red   September      59
8     Male     Blue        July      60
9     Male     Blue         May      58
10  Female      Red    October       60
11    Male    Black   September      65
12    Male    Green    December      85
13    Male    Black       April      72
14    Male    Green    January       90
15    Male   Yellow   November       90
16    Male    Black      August      54
17    Male    Black     January      82
18    Male  Mustard   December       60
19  Female    Black    October       76
20    Male    Black   February       67
21    Male   Yellow       April      74
22    Male      Red  September       66